package main

import (
	"reflect"
	"strings"
	"testing"
)

func TestLazyList(t *testing.T) {
	var ll List = NewLazyList(EvalerFunc("__func__", testCounter, AnyArgs, TypeList), []Param{{V: Int64(0), T: TypeInt}}, false)
	res := make([]Expr, 0, 10)
	for !ll.Empty() {
		val, err := ll.Head()
		if err != nil {
			t.Fatalf("Head() failed: %v", err)
		}
		res = append(res, val.V)
		ll, err = ll.Tail()
		if err != nil {
			t.Fatalf("Tail() failed: %v", err)
		}
	}
	exp := []Expr{
		Int64(1),
		Int64(2),
		Int64(3),
		Int64(4),
		Int64(5),
		Int64(6),
		Int64(7),
		Int64(8),
		Int64(9),
		Int64(10),
	}
	if !reflect.DeepEqual(exp, res) {
		t.Errorf("Incorrect sequence generated by LazyList: expected %v, actual %v", exp, res)
	}
}

// 1..10 generator
func testCounter(args []Param) (*Param, error) {
	prev := int64(args[0].V.(Int64))
	if prev >= 10 {
		return &Param{V: QEmpty, T: TypeList}, nil
	}
	s := &Sexpr{
		List:   []Expr{Int64(prev + 1)},
		Quoted: true,
	}
	return &Param{V: s, T: TypeList}, nil
}

func TestLazyListState(t *testing.T) {
	var ll List = NewLazyList(EvalerFunc("fibGen", fibGen, AnyArgs, TypeList), []Param{{V: QList(Int64(1), Int64(1)), T: TypeList}}, false)
	res := make([]Expr, 0, 10)
	for i := 0; i < 6; i++ {
		val, err := ll.Head()
		if err != nil {
			t.Fatalf("Head() failed: %v", err)
		}
		res = append(res, val.V)
		ll, err = ll.Tail()
		if err != nil {
			t.Fatalf("Tail() failed: %v", err)
		}
	}
	exp := []Expr{
		Int64(1),
		Int64(2),
		Int64(3),
		Int64(5),
		Int64(8),
		Int64(13),
	}
	if !reflect.DeepEqual(exp, res) {
		t.Errorf("Incorrect sequence generated by LazyList: expected %v, actual %v", exp, res)
	}
}

func fibGen(args []Param) (*Param, error) {
	state := args[0].V.(*Sexpr)
	a := int64(state.List[0].(Int64))
	b := int64(state.List[1].(Int64))
	a, b = b, a+b
	s := &Sexpr{
		List: []Expr{
			Int64(a),
			QList(Int64(a), Int64(b)),
		},
		Quoted: true,
	}
	return &Param{V: s, T: TypeList}, nil
}

func TestLazyListFiniteString(t *testing.T) {
	ll := NewLazyList(EvalerFunc("__func__", testCounter, AnyArgs, TypeAny), []Param{{V: Int64(0), T: TypeInt}}, false)
	var buffer strings.Builder
	ll.Print(&buffer)
	act := buffer.String()
	exp := "'(1 2 3 4 5 6 7 8 9 10)"
	if act != exp {
		t.Errorf("Incorrect string representation of LazyList: expected %q, actual %q", exp, act)
	}
}
